In [1]:
import numpy as np
import math

def Choleskydecomp(A):
    L = np.copy(A)
    n = len(A)
    L[0][0] = math.sqrt(L[0,0]) 
    for j in range(n):
        L[j][j] = L[j][j]
        for k in range(j):
            L[j][j] -= (L[j][k])**2
        L[j][j] = math.sqrt(L[j][j])
        for i in range(j+1,n):
            L[i][j] = L[i][j]
            for k in range(j):
                L[i][j] -= L[i][k]*L[j][k]
            L[i][j] /= L[j][j]
    for i in range(n-1):
        for j in range(i+1,n):
            L[i][j] = 0.0
    return L

def Lforwardsub (L,b):
    n = len(L)
    y = np.zeros(n)
    y[0] = b[0]/L[0][0]
    for i in range(1,n):
        y[i] = b[i]
        for j in range(i):
            y[i] = y[i] - L[i][j]*y[j]
        y[i] = y[i]/L[i][i]
    return y
            
def LTbackwardsub (L,y):
    n = len(L)
    x = np.zeros(n)
    x[n-1] = y[n-1]/L[n-1][n-1]
    for i in range(n-2,-1,-1):
        x[i] = y[i]
        for j in range(i+1,n):
            x[i] = x[i] - L[j][i]*x[j]
        x[i] /= L[i][i]
    return x
    
def LLTsolve(L,b):
    y = Lforwardsub(L,b)
    x = LTbackwardsub(L,y)
    return x
     

A = np.matrix([[1.0,1.0,1.0,1.0],[1.0,4.0,4.0,4.0],[1.0,4.0,9.0,9.0],[1.0,4.0,9.0,18.0]])
L = Choleskydecomp(A)
print(L)
print(L.dot(np.transpose(L)))
print(A)
b = np.array([1.0,0.0,0.0,0.0])
x = LLTsolve(L,b)
print(x)
print(A.dot(x))


[[ 1.          0.          0.          0.        ]
 [ 1.          1.73205081  0.          0.        ]
 [ 1.          1.73205081  2.23606798  0.        ]
 [ 1.          1.73205081  2.23606798  3.        ]]
[[  1.   1.   1.   1.]
 [  1.   4.   4.   4.]
 [  1.   4.   9.   9.]
 [  1.   4.   9.  18.]]
[[  1.   1.   1.   1.]
 [  1.   4.   4.   4.]
 [  1.   4.   9.   9.]
 [  1.   4.   9.  18.]]
[  1.33333333e+00  -3.33333333e-01   4.44089210e-17   0.00000000e+00]
[[  1.00000000e+00  -2.66453526e-16  -4.44089210e-17  -4.44089210e-17]]
