In [5]:
import numpy as np

def LUdecomp(A):
    LU=np.copy(A)
    n =len(A)
    sign = 1.0
    p = range(n)
    for j in range(n-1):
        maxi = j
        c = abs(LU[j][j])
        for i in range(j+1,n):
            c1 = abs(LU[i][j])
            if (c1 > c):
                c = c1
                maxi = i
        if (j != maxi):
            sign *= -1.0
            itmp = p[j]
            p[j] = p[maxi]
            p[maxi] = itmp
            for k in range(n):
                dtmp = LU[maxi][k]
                LU[maxi][k] = LU[j][k]
                LU[j][k] = dtmp
        for i in range(j+1,n):
            LU[i][j] = LU[i][j]/LU[j][j]
            for k in range(j+1,n):
                LU[i][k] = LU[i][k] - LU[i][j]*LU[j][k]
    return LU,p,sign

def LUforwardsub (L,p,b):
    n = len(L)
    y = np.zeros(n)
    y[0] = b[p[0]]
    for i in range(1,n):
        y[i] = b[p[i]]
        for j in range(i):
            y[i] = y[i] - L[i][j]*y[j]
    return y
            
def LUbackwardsub (U,y):
    n = len(U)
    x = np.zeros(n)
    x[n-1] = y[n-1]/U[n-1][n-1]
    for i in range(n-2,-1,-1):
        x[i] = y[i]
        for j in range(i+1,n):
            x[i] = x[i] - U[i][j]*x[j]
        x[i] /= U[i][i]
    return x
    
def LUsolve(LU,p,b):
    y = LUforwardsub(LU,p,b)
    x = LUbackwardsub(LU,y)
    return x

def LUdet(LU,sign):
    n = len(LU)
    det = sign
    for i in range(n):
        det = det * LU[i][i]
    return det

def LUinverse(LU,p):
    n = len(LU)
    e = np.zeros(n)
    I = np.zeros((n,n))
    for j in range(n):
        e[j] = 1.0
        x = LUsolve(LU,p,e)
        for i in range(n):
            I[i][j] = x[i]
        e[j] = 0.0
    return I

def LUgetL(LU):
    L=np.copy(LU)
    n =len(LU)
    for i in range(n):
        L[i][i] = 1.0
        for j in range(i+1,n):
            L[i][j] = 0.0
    return L
    
def LUgetU(LU):
    U=np.copy(LU)
    n =len(LU)
    for i in range(1,n):
        for j in range(i):
            U[i][j] = 0.0
    return U
    
def LUgetP(p):
    n =len(p)
    P=np.zeros((n,n))
    for i in range(n):
        P[i][p[i]] = 1.0
    return P
    
A = np.matrix([[2.0,1.0,1.0,0.0],[4.0,3.0,3.0,1.0],[8.0,7.0,9.0,5.0],[6.0,7.0,9.0,8.0]])
LU,p,sign = LUdecomp(A)
print(LU)
print(p)
print(sign)

L = LUgetL(LU)
U = LUgetU(LU)
P = LUgetP(p)
print(L)
print(U)
print(P)
print(P.dot(A))
print(L.dot(U))

b = np.array([1.0,0.0,0.0,0.0])
print(b)
x = LUsolve(LU,p,b)
print(x)
IA = LUinverse(LU,p)
print(IA)
print(np.dot(A,IA))
print(LUdet(LU,sign))

[[ 8.          7.          9.          5.        ]
 [ 0.75        1.75        2.25        4.25      ]
 [ 0.5        -0.28571429 -0.85714286 -0.28571429]
 [ 0.25       -0.42857143  0.33333333  0.66666667]]
[2, 3, 1, 0]
-1.0
[[ 1.          0.          0.          0.        ]
 [ 0.75        1.          0.          0.        ]
 [ 0.5        -0.28571429  1.          0.        ]
 [ 0.25       -0.42857143  0.33333333  1.        ]]
[[ 8.          7.          9.          5.        ]
 [ 0.          1.75        2.25        4.25      ]
 [ 0.          0.         -0.85714286 -0.28571429]
 [ 0.          0.          0.          0.66666667]]
[[ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]]
[[ 8.  7.  9.  5.]
 [ 6.  7.  9.  8.]
 [ 4.  3.  3.  1.]
 [ 2.  1.  1.  0.]]
[[ 8.  7.  9.  5.]
 [ 6.  7.  9.  8.]
 [ 4.  3.  3.  1.]
 [ 2.  1.  1.  0.]]
[ 1.  0.  0.  0.]
[ 2.25 -3.   -0.5   1.5 ]
[[  2.25000000e+00  -7.50000000e-01  -2.50000000e-01   2.50000000e-01]
 [ -3.00000000e+00   

In [6]:
import numpy as np
import scipy
import scipy.linalg

a = np.matrix([[2.0,1.0,1.0,0.0],[4.0,3.0,3.0,1.0],[8.0,7.0,9.0,5.0],[6.0,7.0,9.0,8.0]])
p,l,u = scipy.linalg.lu(a)

print(p)
print(l)
print(u)

[[ 0.  0.  0.  1.]
 [ 0.  0.  1.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]]
[[ 1.          0.          0.          0.        ]
 [ 0.75        1.          0.          0.        ]
 [ 0.5        -0.28571429  1.          0.        ]
 [ 0.25       -0.42857143  0.33333333  1.        ]]
[[ 8.          7.          9.          5.        ]
 [ 0.          1.75        2.25        4.25      ]
 [ 0.          0.         -0.85714286 -0.28571429]
 [ 0.          0.          0.          0.66666667]]
