In [9]:
import numpy as np

def power_method(A, x0, MaxSteps):
    x1 = x0
    for i in range(MaxSteps):
        x1 = A*x1
        x1 = x1/np.linalg.norm(x1)
        lambda1 = (np.transpose(A*x1)*x1)[0,0]
    return x1,lambda1

A  = np.matrix([[-2.0,1.0],[1.0,-2.0]])
x0 = np.matrix([[1.0],[0.0]])

v1,l1 = power_method(A,x0,100)
print(v1)
print(l1)

print(np.linalg.eig(A))

B = A - l1*v1*np.transpose(v1)
print(B)
v2,l2 = power_method(B,x0,100)
print(v2)
print(l2)

print(np.linalg.eig(B))


[[ 0.70710678]
 [-0.70710678]]
-3.0
(array([-1., -3.]), matrix([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))
[[-0.5 -0.5]
 [-0.5 -0.5]]
[[ 0.70710678]
 [ 0.70710678]]
-1.0
(array([ -1.38777878e-15,  -1.00000000e+00]), matrix([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]))
