In [4]:
import numpy as np
import math

def Choleskydecomp(A):
    L = np.copy(A)
    n = len(A)
    L[0][0] = math.sqrt(L[0,0]) 
    for j in range(n):
        L[j][j] = L[j][j]
        for k in range(j):
            L[j][j] -= (L[j][k])**2
        L[j][j] = math.sqrt(L[j][j])
        for i in range(j+1,n):
            L[i][j] = L[i][j]
            for k in range(j):
                L[i][j] -= L[i][k]*L[j][k]
            L[i][j] /= L[j][j]
    for i in range(n-1):
        for j in range(i+1,n):
            L[i][j] = 0.0
    return L

A = np.matrix([[1.0,1.0,1.0,1.0],[1.0,4.0,4.0,4.0],[1.0,4.0,9.0,9.0],[1.0,4.0,9.0,18.0]])
L = Choleskydecomp(A)
print(L)
print(L.dot(np.transpose(L)))
print(A)


[[ 1.          0.          0.          0.        ]
 [ 1.          1.73205081  0.          0.        ]
 [ 1.          1.73205081  2.23606798  0.        ]
 [ 1.          1.73205081  2.23606798  3.        ]]
[[  1.   1.   1.   1.]
 [  1.   4.   4.   4.]
 [  1.   4.   9.   9.]
 [  1.   4.   9.  18.]]
[[  1.   1.   1.   1.]
 [  1.   4.   4.   4.]
 [  1.   4.   9.   9.]
 [  1.   4.   9.  18.]]
