## INF1608 - Análise Numérica - 2017.1
## Departamento de Informática - PUC-Rio 
## Prof. Hélio Lopes - lopes@inf.puc-rio.br
## http://www.inf.puc-rio.br/~lopes


## Aluno: Leonardo Wajnsztok
## Matrícula:  1312737
## Lista 2

1) Modifique a implementação da decomposição LU para incluir a permutação de linhas, obtendo a decomposição PA=LU.

2) Implemente a função LUsolve que resolve o sistema Ax=b, tendo em mão a deomposição PA=LU.

3) Utilize as implementações dos items 1 e 2 da lista para resolver o sistema Ax = b, onde:

A = np.matrix([[1.,0.,0.,1.],[-1.,1.,0.,1.],[-1.,-1.,1.,1.],[-1.,-1.,-1.,1.]])
e
b = np.array([1.,1.,2.,0.])


In [1]:
import numpy as np
import matplotlib 
import matplotlib.pylab as plt

%matplotlib inline

In [2]:
def LU_decomposition(a):
    LU = np.copy(A)
    n = len(A)

    P = [i for i in range(n)]
    for j in range(n):
        max_id = max(range(j, n), key=lambda i: abs(A[P[i], j]))
        if j != max_id:
            P[j], P[max_id] = P[max_id], P[j]

    for i in range(n):
        LU[i,:] = A[P[i],:]
    
    for j in range(n-1):
        for i in range(j+1,n):
            LU[i][j] = LU[i][j]/LU[j][j]
            for k in range(j+1,n):
                LU[i][k] = LU[i][k] - LU[i][j]*LU[j][k]
    return P, LU

In [3]:
def LU_forward_substitution(L, b):
    n = len(L)
    y = np.zeros(n)
    y[0] = b[0]
    for i in range(1,n):
        y[i] = b[i]
        for j in range(i):
            y[i] = y[i] - L[i][j]*y[j]
    return y

    

In [4]:
def LU_backward_substitution(U, y):
    n = len(U)
    x = np.zeros(n)
    x[n-1] = y[n-1]/U[n-1,n-1]
    for i in range(n-2,-1,-1):
        x[i] = y[i]
        for j in range(i+1,n):
            x[i] = x[i] - U[i][j]*x[j]
        x[i] /= U[i][i]
    return x

In [5]:
def LU_solve(P, LU, b):
    n = len(P)
    _b = np.copy(b)
    for i in range(n):
       b[i] = _b[P[i]] 
    
    y = LU_forward_substitution(LU,b)
    x = LU_backward_substitution(LU,y)
    return x

In [8]:

A = np.matrix([[1.,0.,0.,1.],[-1.,1.,0.,1.],[-1.,-1.,1.,1.],[-1.,-1.,-1.,1.]])
b = np.array([1.,1.,2.,0.])
print A

P, LU = LU_decomposition(A)
x = LU_solve(P, LU, b)

print x
print P
print LU
print np.dot(A, x) == b




[[ 1.  0.  0.  1.]
 [-1.  1.  0.  1.]
 [-1. -1.  1.  1.]
 [-1. -1. -1.  1.]]
[ 0.  0.  1.  1.]
[0, 1, 2, 3]
[[ 1.  0.  0.  1.]
 [-1.  1.  0.  2.]
 [-1. -1.  1.  4.]
 [-1. -1. -1.  8.]]
[[ True  True  True  True]]
